# .streamlit/config.toml
[theme]
primaryColor = "#405DE6"             # Instagram‑purple accent
backgroundColor = "#FFFFFF"          # App background
secondaryBackgroundColor = "#FFFFFF" # Sidebar / cards
textColor = "#111111"                # Dark text
font = "sans serif"
